config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  devise_for :users
  resources :users, only: %i[index]
  resources :groups, only: %i[index new create show edit update]
  resources :transactions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  mount_uploader :icon, ImageUploader

  validates :name, presence: true

  belongs_to :user
  has_many :transactions

  def self.find_by_first_letter(letter)
    where('name LIKE ?', "#{letter}%").order('name ASC')
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  validates :name, presence: true
  validates :amount, presence: true

  belongs_to :author, class_name: 'User'
  belongs_to :group, optional: true

  scope :without_group, ->(author_id) { where('group_id IS NULL and author_id=?', author_id) }
  scope :with_group, ->(author_id) { where('group_id > 0 and author_id=?', author_id) }
  scope :ordered_by_most_recent, -> { order(created_at: :desc) }
  scope :expense_per_group, ->(author_id) { left_outer_joins(:group).where('author_id=?', author_id).group('groups.name').select("groups.name as group_name, sum(amount) as sum") }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true

  has_many :groups
  has_many :transactions, class_name: 'Transaction', foreign_key: 'author_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = Group.all.find_by_first_letter(params[:letter])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_param)
    @group.user = current_user
    if @group.save
      redirect_to groups_path, notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  def show
    @group = Group.find(params[:id])
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    @group.update(group_param)
    redirect_to group_path(@group)
  end

  private

  def group_param
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:view]
      @t1 = Transaction.with_group(current_user.id).ordered_by_most_recent
      render 'one_page'
    else
      @t2 = Transaction.without_group(current_user.id).ordered_by_most_recent
      render 'another_page'
    end
  end

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.new(transaction_param)
    @transaction.author_id = current_user.id
    if @transaction.save
      redirect_to root_path, notice: 'New transaction was successfully created.'
    else
      render :new
    end
  end

  def show
    @transaction = Transaction.find(params[:id])
  end

  def edit
    @transaction = Transaction.find(params[:id])
  end

  def update
    @transaction = Transaction.find(params[:id])
    @transaction.update(transaction_param)
    redirect_to transaction_path(@transaction)
  end

  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy
    flash[:notice] = "Transaction successfully Deleted"
    redirect_to root_path
  end

  private

  def transaction_param
    params.require(:transaction).permit(:name, :amount, :group_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @expense_per_group = Transaction.expense_per_group(current_user.id)
  end

  def show
    # @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/edit.html.erb
<div class='custom-bg2 text-light d-flex justify-content-between rounded col-12 col-md-6 center mb-5 shadow-sm bg-white'>
  <h1 class="center my-3">Edit group</h1>
</div>

 <div class="bg-danger text-light mt-1 center rounded"> 
        <% if @group.errors.any? %>
          <% @group.errors.full_messages.each do |error| %>
            <%= error %>
          <% end %>
        <% end %>  
     </div>

<div class='custom-bg3 rounded text-light font-weight-bold'>  
  <div class="pb-4">
    <%=form_for @group do |f|%>        

      <div class="field">
        <%=f.label :name%>
        <%=f.text_field :name%>
      </div>
      
      <div class="field">
        <fieldset>
          <%= f.label :icon, 'icon' %>
          <%= f.hidden_field :icon_cache %>
          <%= f.file_field :icon%>
        </fieldset>
      </div>
      
      <div class="actions">
        <%=f.submit "Update", :class => 'btn btn-primary btn-lg mt-2'%>
      </div>  
    <%end%> 
  </div>  
</div>

<%= link_to "Back", :back, :class => 'text-dark' %>

app/views/groups/index.html.erb
<div class='action d-flex mb-3'>
  <%= link_to 'Create a new Group', new_group_path, :class => 'btn btn-primary col-12 col-md-4 center font-weight-bold' %> 
</div>

<div class='custom-bg2 d-flex justify-content-between rounded col-12 col-md-4 center mb-5 shadow-sm bg-white'>
    <p class = 'center py-3 text-light font-weight-bold'> All Groups:</p> 
</div>

<div class="center"> 
  <% @groups.each do |group| %>
    <%= link_to group_path(group.id)do %>
      <div class="card mb-3 center custom-bg" style="max-width: 540px;">
        <div class="row">
          <div class="col-3">
            <img src="<%=group.icon%>" class="icon" alt="">
          </div>
          <div class="col-8">
            <div class="card-body">
            <h5 class="card-title"><%= group.name %></h5>        
            </div>
          </div>
        </div>
      </div>  
    <% end %>   
  <% end %>   
</div>

<%= link_to "Back", :back, :class => 'text-dark' %>

app/views/groups/new.html.erb
<div class='custom-bg2 text-light d-flex justify-content-between rounded col-12 col-md-6 center mb-5 shadow-sm bg-white'>
  <h1 class="center my-3">New group</h1>
</div>

 <div class="bg-danger text-light mt-1 center rounded"> 
        <% if @group.errors.any? %>
          <% @group.errors.full_messages.each do |error| %>
            <%= error %>
          <% end %>
        <% end %>  
     </div>

<div class='custom-bg3 rounded text-light font-weight-bold'>  
  <div class="pb-4">
    <%=form_for @group do |f|%>        

      <div class="field">
        <%=f.label :name%>
        <%=f.text_field :name%>
      </div>
      
      <div class="field">
        <fieldset>
          <%= f.label :icon, 'icon' %>
          <%= f.hidden_field :icon_cache %>
          <%= f.file_field :icon%>
        </fieldset>
      </div>
      
      <div class="actions">
        <%=f.submit "Create", :class => 'btn btn-primary btn-lg mt-2'%>
      </div>  
    <%end%> 
  </div>  
</div>

<%= link_to "Back", :back, :class => 'text-dark' %>

app/views/groups/show.html.erb
 <div class="center">
    <div class='custom-bg2 d-flex justify-content-around rounded col-12 col-md-6 center mb-3 shadow-sm text-light'>
      <h4 class ="mt-4 text-light font-weight-bold"><%= "Group Name: #{@group.name}" %></h4>
      <img src="<%=@group.icon%>" class="icon mb-2" alt="">
    </div>   
    
    <ul>
      <% @group.transactions.each do |t|%>
        <div class='custom-bg d-flex flex-column col-12 col-md-5 rounded center mb-5 shadow-sm bg-white'>
          <div class = "d-flex justify-content-between">
            <p class ="mt-3"><%= t.name %><p>
            <p class ="mt-3">$<%= t.amount %></p>   
          </div>    
          <div class = "d-flex justify-content-between">          
            <p class =''>Creator: <%=t.author.name %><p>
            <p><small class="text-muted"><%=t.created_at.strftime("%b %d, %Y")%></small></p>
          </div>
        </div>  
      <%end%> 
    </ul>
    <p class="center mt-1"><%= link_to "Edit group details", edit_group_path(@group), :class => ' text-dark font-weight-bold'%></p>
 </div>
 <%= link_to "Back", :back, :class => 'text-dark' %>
 

app/views/layouts/_footer.html.erb
<footer  class="pt-3 bg-dark text-white fixed-bottom">
  <div class="container text-center">
    <small>Copyright &copy; All rights reserved - by LamiaSristy <%= link_to "Expanzee", "#", class: "text-white" %></small>
    <ul class="list-unstyled">
       <li>
         <i class="fab fa-facebook-square"></i>
          <i class="fab fa-twitter"></i>
          <i class="fab fa-instagram "></i>
           <i class="fab fa-tumblr "></i>
           <i class="fab fa-linkedin-in "></i>
       </li>
    </ul> 
  </div>                
</footer>

app/views/layouts/_message.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>  

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
   <%= link_to 'Expanzee', root_path, :class => 'navbar-brand', :id => 'logo' %> 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#"><span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"></a>
      </li>     
    </ul>
    <ul class="navbar-nav float-right">
    <% if user_signed_in? %>
      <li class="nav-item">           
        <a class="nav-link" href="#"><strong><%= current_user.name %></strong></a>       
      </li>
      <li class="nav-item">
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-link' %> 
      </li>
      <li class="nav-item">
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link'  %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link'  %> 
      </li>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, :class => 'nav-link'  %>
      </li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TransactionsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">      
      <script src="https://kit.fontawesome.com/867f1dd431.js" crossorigin="anonymous"></script>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
      <%# <script type="text/javascript" src="app/javascript/pie-chart.js"></script> %>
  </head>

  <body>
    <%= render 'layouts/navigation'%> 
    <%= render 'layouts/message'%>
    <div id = 'page-content'>
      <%= yield %>
    </div> 
    <%= render 'layouts/footer'%>  
  </body>
</html>

app/views/transactions/another_page.html.erb
<div class='action d-flex mb-3'>
  <%= link_to 'Add new transaction', new_transaction_path, :class => 'center btn btn-primary btn-lg col-12 col-md-5 font-weight-bold' %> 
</div>

<div class='center'>
  <div class='custom-bg d-flex justify-content-between rounded col-12 col-md-5 center mb-5 shadow-sm bg-white'>
    <p class ="mt-3"><small>External Transactions </small><p>
    <p class ="mt-3"><small>Total Expence:</small> $<%= @t2.sum(:amount) %></p>   
  </div>

  <% @t2.each do |t| %>
    <%= link_to transaction_path(t.id) do %>
      <div class='custom-bg d-flex flex-column col-12 col-md-5 rounded center mb-5 shadow-sm bg-white'>
        <div class = "d-flex justify-content-between">
          <p class ="mt-3"><%= t.name %><p>
          <p class ="mt-3">$<%= t.amount %></p>   
        </div>    
        <div class = "d-flex justify-content-end">
          <p><small class="text-muted"><%=t.created_at.strftime("%b %d, %Y")%></small></p>
        </div>
      </div>
    <%end%>  
  <%end%>

  <%= link_to "Back", :back, :class => 'text-dark' %>
  

app/views/transactions/edit.html.erb
<div class='custom-bg2 text-light d-flex justify-content-between rounded col-12 col-md-6 center mb-5 shadow-sm bg-white'>
  <h1 class="center my-3">Edit Transaction</h1>
</div>
 
  <div class="bg-danger text-light mt-1 center rounded"> 
      <% if @transaction.errors.any? %>
        <% @transaction.errors.full_messages.each do |error| %>
          <%= error %>
        <% end %>
      <% end %>  
  </div>   

  <div class='custom-bg3 rounded text-light font-weight-bold'>
    <div class="pb-4">
      <%=form_for @transaction do |f|%>     
        <div class="field">
          <%=f.label :name%>
          <%=f.text_field :name%>
        </div>

        <div class="field">
          <%=f.label :amount%>
          <%=f.number_field :amount%>
        </div>
        
        <div class="field">
          <%=f.label :select_group%>    
          <%=select("transaction", "group_id", Group.all.collect {|g|[g.name, g.id] }, { include_blank: true })%>
        </div>

        <div class="actions">
          <%=f.submit "Update", :class => 'btn btn-primary btn-lg'%>
        </div>
      <%end%> 
    </div>
  </div>

  <%= link_to "Back", :back, :class => 'text-dark' %>

app/views/transactions/new.html.erb
<div class='custom-bg2 text-light d-flex justify-content-between rounded col-12 col-md-6 center mb-5 shadow-sm bg-white'>
  <h1 class="center my-3">New Transaction</h1>
</div>
 
  <div class="bg-danger text-light mt-1 center rounded"> 
      <% if @transaction.errors.any? %>
        <% @transaction.errors.full_messages.each do |error| %>
          <%= error %>
        <% end %>
      <% end %>  
  </div>   

  <div class='custom-bg3 rounded text-light font-weight-bold'>
    <div class="pb-4">
      <%=form_for @transaction do |f|%>     
        <div class="field">
          <%=f.label :name%>
          <%=f.text_field :name%>
        </div>

        <div class="field">
          <%=f.label :amount%>
          <%=f.number_field :amount%>
        </div>
        
        <div class="field">
          <%=f.label :select_group%>    
          <%=select("transaction", "group_id", Group.all.collect {|g|[g.name, g.id] }, { include_blank: true })%>
        </div>

        <div class="actions">
          <%=f.submit "Create", :class => 'btn btn-primary btn-lg'%>
        </div>
      <%end%> 
    </div>
  </div>

  <%= link_to "Back", :back, :class => 'text-dark' %>

app/views/transactions/one_page.html.erb
<div class='action d-flex mb-3'>
  <%= link_to 'Add new transaction', new_transaction_path, :class => 'center btn btn-primary btn-lg col-12 col-md-5 font-weight-bold' %> 
</div>

<div class='center'>
  <div class='custom-bg2 text-light d-flex justify-content-between rounded col-12 col-md-5 center mb-5 shadow-sm bg-white'>
    <p class ="mt-3"><small>All Transactions With Group.</small><p>
    <p class ="mt-3"><small>Total Expence:</small> $<%= @t1.sum(:amount) %></p>   
  </div>

  <% @t1.each do |t| %>
     <%= link_to transaction_path(t.id) do %> 
       <div class="card mb-3 center custom-bg " style="max-width: 540px;">
        <div class="row">
          <div class="col-3">
            <img src="<%=t.group.icon%>" class="icon" alt="">
          </div>
          <div class="col-8">
            <div class="card-body">
              <div class = "d-flex justify-content-between">
                <h5 class="card-title"><%= t.name %></h5>  
                <p class="card-text">$<%= t.amount %></p>
              </div>          
              <p class="card-text d-flex justify-content-start"><small class="text-muted"><%=t.created_at.strftime("%b %d, %Y")%></small></p>      
            </div>
          </div>
        </div>
      </div> 
     <%end%>   
  <%end%>

  <%= link_to "Back", :back, :class => 'text-dark' %>

app/views/transactions/show.html.erb
<div class="center">

      <div class='custom-bg2 d-flex justify-content-around rounded col-12 col-md-6 center mb-3 shadow-sm text-light'>  
        <h4 class ="mt-4 text-light font-weight-bold"><%= "Transaction Details" %></h4>      
      </div> 

  <div class ='jumbotron font_weight_bold'>
    <p class='center'>Transaction Name: <%=@transaction.name%></p>
    <p class='center'>Amount: <%=@transaction.amount%></p>
    <p class='center'>Creator :<%=@transaction.author.name%></p>
    <p class='center'>Date:<small><%=@transaction.created_at.strftime("%b %d, %Y")%></small></p>   
  </div>

  <p class="center mt-1"><%= link_to "Edit", edit_transaction_path(@transaction), :class => 'text-dark font-weight-bold' %></p>
  <p class="center mt-1"><%= link_to "Delete", transaction_path(@transaction), method: :delete, data: { confirm: 'Are you certain you want to delete this?'}, :class => 'text-dark font-weight-bold'%></p>

</div>

<%= link_to "Back", :back, :class => 'text-dark' %>

app/views/users/_user.html.erb
<%unless current_user == user%>
<li>
  Name: <%= user.name %>
  <span class="profile-link">
    <%= link_to 'See Profile',  user_path(user), class: 'profile-link' %>
  </span> 
</li>
<%end%>

app/views/users/index.html.erb
<div class='custom-bg2 text-light d-flex justify-content-between rounded col-12 col-md-6 center mb-5 shadow-sm bg-white'>
  <h1 class="center my-3">Welcome</h1>
</div>

<div class=" center py-5 shadow-lg bg-white rounded col-12 col-md-6  custom-bg">
    <%= link_to transactions_path(view: true), :class => 'text-light' do %>
      <div class='center py-2 mb-2 mx-2 transition shadow rounded custom-bg2'>
        <p class = 'mt-2'>All  my transactions</p>
      </div>
    <%end%>
    <%= link_to transactions_path, :class => 'text-light' do %>
      <div class='center py-2 mb-2 mx-2 transition shadow rounded custom-bg2'>
        <p class = 'mt-2'>All my external transactions</p>
      </div>
    <%end%>
     <%= link_to groups_path, :class => 'text-light' do %>
      <div class='center py-2 mb-2 mx-2 transition shadow rounded custom-bg2'> 
        <p class = 'mt-2'>All Groups</p>
      </div>
    <%end%>


</div class ='col-12 col-md-6 center'>
  <p class = 'center text-dark font-weight-bold mt-3'>Group-wise Transaction</p>
  <div id="piechart" data = "<%= @expense_per_group.to_json %>"></div>
  <div><%= javascript_pack_tag 'piechart' %></div>
</div>